In [1]:
import numpy
a = numpy.array([1, 2, 3])

In [2]:
print(a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
import numpy as np
a = np.array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [8]:
b = np.array([(2, 5, 7), (5, 3, 9), (4, 6, 5)])

In [9]:
print(b)

[[2 5 7]
 [5 3 9]
 [4 6 5]]


In [11]:
c = np.zeros((4, 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
d = np.ones((5, 7))
print(d)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [13]:
e = np.eye((4))
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
f = np.eye((10))
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
b.max()

9

In [16]:
b.min()

2

In [17]:
b.sum()

46

In [18]:
b.mean()

5.111111111111111

In [19]:
b.std()

1.9688939051854832