In [1]:
import pandas as pd
alunos = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'], 
          'Nota':[4, 7, 5.5, 9], 
          'Aprovado':['Não', 'Sim', 'Não', 'Sim']}

In [2]:
dataframe = pd.DataFrame(alunos);

In [3]:
print(dataframe)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim


In [4]:
objeto1 = pd.Series([2, 6, 7, 10, 5])
print(objeto1)

0     2
1     6
2     7
3    10
4     5
dtype: int64


In [20]:
import numpy as np
array1 = np.array([7, 6, 9, 13, 1]);
array2 = np.array([(2, 6, 9, 10, 5), (6, 12, 2, 9, 10)]);
print(array1)
print(array2)

[ 7  6  9 13  1]
[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


In [21]:
objeto2 = pd.Series(array1);
print(objeto2);

0     7
1     6
2     9
3    13
4     1
dtype: int32
